server:
  port: 8089
  address: 0.0.0.0
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
#    url: jdbc:postgresql://localhost:5433/madrascheck
#    username: madrascheck
#    password: 20260209
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
    open-in-view: false

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  connection:
    codeTtlSeconds: 600
    codePrefix: "KSB"
    cleanupIntervalSeconds: 60

springdoc:
  swagger-ui:
    enabled: false

